### ISSUE TITLE
Docker image not working

### ISSUE THREAD

**Issue by LuisSoares** [genepattern/genepattern-notebook#1]
I can't seem to get the latest genepattern-notebook docker image to work in Kitematic, starting the image states 

> Running as root is not recommended. Use --allow-root to bypass.

And automatically stops.

**Comment by tmtabor** [comment]
Since you've closed the ticket, I assume that you figured it out. But if you still need help, let me know.

**Comment by LuisSoares** [comment]
I assume that the docker image doesn't work for me because Kitematic on my windows machine only works in virtualbox, in which the docker file seems to not work properly (I get the Running as root is not recommended. Use --allow-root to bypass.). Also I think that the latest  version of jupyter (5.0?) breaks the compatibility with the gene-pattern widgets, I can't seem to get the javascript to work (all i get is 404 errors and javascript log console errors.

**Comment by tmtabor** [comment]
I have confirmed that there was an issue with the GenePattern Notebook docker container's permissions. I have updated the container in a way that should fix the bug. Let me know if it still doesn't work for you. 

Thanks for finding this!

**Comment by LuisSoares** [comment]
Cool, it now works, thanks for the help Thorin.
